// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rgbvnavluyzspducztpo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJnYnZuYXZsdXl6c3BkdWN6dHBvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3OTcyMjcsImV4cCI6MjA3MTM3MzIyN30.ehs2GWcLqewJdz8r9zAD_grWvqkTtSXrvyRO0zlu9sA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});